name: ML_in_finance
channels:
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.15
  - pandas>=1.0
  - matplotlib>=3.0.0
  - scipy>=1.1.0
  - scikit-learn>=0.22
  - seaborn>=0.9.0
#  - yfinance
  - ipywidgets>=7.2.1
  - pip>=19.0
  - pip:
    - jupyter-contrib-nbextensions>=0.5.1
    - tensorflow>=2.2
    - yfinance
  - openai
  - pypdf
  


